### ISSUE TITLE
Citrus Engine Sourcecode 

### ISSUE THREAD

**Issue by kyle1046** [DaVikingCode/Citrus-Engine#263]
so i downloaded the entire citrus engine sorcecode in a .zip folder removed the old releases from it and tried adding it into flash builder but it doesn't seam to work how do i get it to work, also video is my friend

**Comment by gsynuh** [comment]
Hi kyle1046.

This is more a question for the forums (http://forum.starling-framework.org/forum/citrus-engine), github issues are for more technical issues with the code or discussions about the code, though they can also be addressed on the forums as well and then we open up issues here to keep track of them.
So I'm closing this one.

 I will not create a video, and I don't use FB.

What you need to know to solve your problem is that the source code is like any other as3 source libraries out there, nothing special - so if the following doesn't help , any video tutorial you can find (since video is your friend) teaching you how to include any source code/ libraries to a project in FB will work. 

As3 files needed are in scr/ and scrlib/ and .swc files are in the lib/ folder, that's all you need to know to build a project using CE properly.

Typically one would create a citrus-engine project, and link that project to your game project (in FDT or intellijIDEA) or in FlashDevelop you'd use classpath to include src/ and srclib/ and right click .swc files in lib/ to add them to libary.

The easy way, but less easy when it comes to updating CE later, is to copy into your current project's src/ folder the contents of both src/ and srclib/ and of course the swcs in lib/ to the corresponding lib/ folder in your game project and make sure those are included in the build.
